// SPDX-License-Identifier: MIT

pragma solidity ^0.8.20;

/**
 * @title Mock ZK Verifier
 * @notice A mock verifier for HackMoney 2026 demo purposes.
 * @dev In production, this would contain the actual Groth16 or UltraPlonk verification logic generated by Noir.
 */

contract ZKVerifier {
    // Dummy verifier function
     
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) public view returns (bool) {

        return true;
    }
}